/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as BrQuizRouteImport } from './routes/br-quiz'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as EnRouteImport } from './routes/en'
import { Route as EnQuizRouteImport } from './routes/en-quiz'
import { Route as EsRouteImport } from './routes/es'
import { Route as EsQuizRouteImport } from './routes/es-quiz'
import { Route as EsQuiz2RouteImport } from './routes/es-quiz2'
import { Route as Es2RouteImport } from './routes/es2'
import { Route as InRouteImport } from './routes/in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PtRouteImport } from './routes/pt'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UkRouteImport } from './routes/uk'
import { Route as UpsellRouteImport } from './routes/upsell'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ApiPublicHublaRouteImport } from './routes/api/public/hubla'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const BrQuizRoute = BrQuizRouteImport.update({
  id: '/br-quiz',
  path: '/br-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const EnQuizRoute = EnQuizRouteImport.update({
  id: '/en-quiz',
  path: '/en-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const EsQuizRoute = EsQuizRouteImport.update({
  id: '/es-quiz',
  path: '/es-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const EsQuiz2Route = EsQuiz2RouteImport.update({
  id: '/es-quiz2',
  path: '/es-quiz2',
  getParentRoute: () => rootRouteImport,
} as any)
const Es2Route = Es2RouteImport.update({
  id: '/es2',
  path: '/es2',
  getParentRoute: () => rootRouteImport,
} as any)
const InRoute = InRouteImport.update({
  id: '/in',
  path: '/in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UkRoute = UkRouteImport.update({
  id: '/uk',
  path: '/uk',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellRoute = UpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHublaRoute = ApiPublicHublaRouteImport.update({
  id: '/api/public/hubla',
  path: '/api/public/hubla',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/br-quiz': typeof BrQuizRoute
  '/clips': typeof ClipsRoute
  '/en': typeof EnRoute
  '/en-quiz': typeof EnQuizRoute
  '/es': typeof EsRoute
  '/es-quiz': typeof EsQuizRoute
  '/es-quiz2': typeof EsQuiz2Route
  '/es2': typeof Es2Route
  '/in': typeof InRoute
  '/privacy': typeof PrivacyRoute
  '/pt': typeof PtRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/uk': typeof UkRoute
  '/upsell': typeof UpsellRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/hubla': typeof ApiPublicHublaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/br-quiz': typeof BrQuizRoute
  '/clips': typeof ClipsRoute
  '/en': typeof EnRoute
  '/en-quiz': typeof EnQuizRoute
  '/es': typeof EsRoute
  '/es-quiz': typeof EsQuizRoute
  '/es-quiz2': typeof EsQuiz2Route
  '/es2': typeof Es2Route
  '/in': typeof InRoute
  '/privacy': typeof PrivacyRoute
  '/pt': typeof PtRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/uk': typeof UkRoute
  '/upsell': typeof UpsellRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/hubla': typeof ApiPublicHublaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/br-quiz': typeof BrQuizRoute
  '/clips': typeof ClipsRoute
  '/en': typeof EnRoute
  '/en-quiz': typeof EnQuizRoute
  '/es': typeof EsRoute
  '/es-quiz': typeof EsQuizRoute
  '/es-quiz2': typeof EsQuiz2Route
  '/es2': typeof Es2Route
  '/in': typeof InRoute
  '/privacy': typeof PrivacyRoute
  '/pt': typeof PtRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/uk': typeof UkRoute
  '/upsell': typeof UpsellRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/hubla': typeof ApiPublicHublaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/br-quiz'
    | '/clips'
    | '/en'
    | '/en-quiz'
    | '/es'
    | '/es-quiz'
    | '/es-quiz2'
    | '/es2'
    | '/in'
    | '/privacy'
    | '/pt'
    | '/refund'
    | '/sitemap.xml'
    | '/store'
    | '/terms'
    | '/uk'
    | '/upsell'
    | '/product/$handle'
    | '/api/public/hubla'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/br-quiz'
    | '/clips'
    | '/en'
    | '/en-quiz'
    | '/es'
    | '/es-quiz'
    | '/es-quiz2'
    | '/es2'
    | '/in'
    | '/privacy'
    | '/pt'
    | '/refund'
    | '/sitemap.xml'
    | '/store'
    | '/terms'
    | '/uk'
    | '/upsell'
    | '/product/$handle'
    | '/api/public/hubla'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/br-quiz'
    | '/clips'
    | '/en'
    | '/en-quiz'
    | '/es'
    | '/es-quiz'
    | '/es-quiz2'
    | '/es2'
    | '/in'
    | '/privacy'
    | '/pt'
    | '/refund'
    | '/sitemap.xml'
    | '/store'
    | '/terms'
    | '/uk'
    | '/upsell'
    | '/product/$handle'
    | '/api/public/hubla'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  BrQuizRoute: typeof BrQuizRoute
  ClipsRoute: typeof ClipsRoute
  EnRoute: typeof EnRoute
  EnQuizRoute: typeof EnQuizRoute
  EsRoute: typeof EsRoute
  EsQuizRoute: typeof EsQuizRoute
  EsQuiz2Route: typeof EsQuiz2Route
  Es2Route: typeof Es2Route
  InRoute: typeof InRoute
  PrivacyRoute: typeof PrivacyRoute
  PtRoute: typeof PtRoute
  RefundRoute: typeof RefundRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  TermsRoute: typeof TermsRoute
  UkRoute: typeof UkRoute
  UpsellRoute: typeof UpsellRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ApiPublicHublaRoute: typeof ApiPublicHublaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/br-quiz': {
      id: '/br-quiz'
      path: '/br-quiz'
      fullPath: '/br-quiz'
      preLoaderRoute: typeof BrQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en-quiz': {
      id: '/en-quiz'
      path: '/en-quiz'
      fullPath: '/en-quiz'
      preLoaderRoute: typeof EnQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es-quiz': {
      id: '/es-quiz'
      path: '/es-quiz'
      fullPath: '/es-quiz'
      preLoaderRoute: typeof EsQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es-quiz2': {
      id: '/es-quiz2'
      path: '/es-quiz2'
      fullPath: '/es-quiz2'
      preLoaderRoute: typeof EsQuiz2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es2': {
      id: '/es2'
      path: '/es2'
      fullPath: '/es2'
      preLoaderRoute: typeof Es2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in': {
      id: '/in'
      path: '/in'
      fullPath: '/in'
      preLoaderRoute: typeof InRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk': {
      id: '/uk'
      path: '/uk'
      fullPath: '/uk'
      preLoaderRoute: typeof UkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell': {
      id: '/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof UpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hubla': {
      id: '/api/public/hubla'
      path: '/api/public/hubla'
      fullPath: '/api/public/hubla'
      preLoaderRoute: typeof ApiPublicHublaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  BrQuizRoute: BrQuizRoute,
  ClipsRoute: ClipsRoute,
  EnRoute: EnRoute,
  EnQuizRoute: EnQuizRoute,
  EsRoute: EsRoute,
  EsQuizRoute: EsQuizRoute,
  EsQuiz2Route: EsQuiz2Route,
  Es2Route: Es2Route,
  InRoute: InRoute,
  PrivacyRoute: PrivacyRoute,
  PtRoute: PtRoute,
  RefundRoute: RefundRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  TermsRoute: TermsRoute,
  UkRoute: UkRoute,
  UpsellRoute: UpsellRoute,
  ProductHandleRoute: ProductHandleRoute,
  ApiPublicHublaRoute: ApiPublicHublaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
