// Originally generated by Lovable. Edited on purpose: see the guard below.
import { createMiddleware } from "@tanstack/react-start";
import { isSupabaseConfigured, supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// Being global means it runs for EVERY server function, including the one the
// landing page uses to resolve country and currency. The Supabase client throws
// when its credentials are missing, so an unset members-area variable used to take
// down the whole sales funnel at hydration: the HTML rendered fine and then the
// error boundary replaced it with "This page didn't load".
//
// The funnel does not need Supabase, so a missing or broken session is not an
// error here. It just means no token to attach. Routes that genuinely require
// auth still fail loudly through requireSupabaseAuth on the server.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    if (!isSupabaseConfigured()) return next();

    try {
      const { data } = await supabase.auth.getSession();
      const token = data.session?.access_token;
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
    } catch (error) {
      console.warn("[supabase] could not read the session, continuing anonymously", error);
      return next();
    }
  },
);
